# With a docker image
jobs:
- name: docker-image
  public: true
  plan:
  - task: a-simple-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: uname
        args: [-a]

