# Example with GIT resource
resources:
- name: get-git-repo
  type: git
  source: 
    uri: https://github.com/jhderojasUVa/randomfuckwork.git
    branch: master

jobs:
- name: show-dir-on-repo-and-compile
  public: true
  plan:
  - get: get-git-repo
  # this will show inside the docker the resource git and the content
  - task: get-repo-do-ls
    config:
      platform: linux
      # this is the input!
      inputs:
        - name: get-git-repo
      outputs:
        - name: get-git-repo
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: ls
        args: [-la]
  # let's do a basic compilation!
  - task: compile-react-app
    config:
      platform: linux
      inputs:
        - name: get-git-repo
      image_resource:
        type: docker-image
        source: { repository: node }
      run:
        path: sh
        args:
          - -cx
          - |
            cd get-git-repo
            npm install
            npm run build
