# Starting (hello world)
jobs:
- name: hello-world
  public: true
  plan:
  - task: a-simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello World!"]
