# Time interval job with resource "time"
resources:
- name: every-10s
  type: time
  icon: clock-outline
  source:
    interval: 10s

jobs:
- name: job
  public: true
  plan:
  - get: every-10s
    trigger: true
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello, world!"]
